import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs';
import path from 'path';
import { GitService } from '../../core/git/GitService';
import { AIError } from '../../agent/llm';
import {
  PlanWorkflow,
  GitWorkflowSession,
  WorkflowConfig
} from '../../core/workflows';
import { CapabilityLevel } from '../../core/capability/CapabilityLevel';
import { getCapabilityLevelDisplay } from './utils';

const DEFAULT_PLAN_PROMPT = '分析项目现状并规划下一步开发任务';
const METADATA_PREFIX = '>';

async function resolveUserPrompt(cliPrompt: string, todoPath: string): Promise<{ prompt: string; fromFile: boolean }> {
    if (cliPrompt) {
        return { prompt: cliPrompt, fromFile: false };
    }

    try {
        await fs.promises.access(todoPath, fs.constants.F_OK);
        const content = await fs.promises.readFile(todoPath, 'utf8');

        const lines = content.split('\n');
        let startIndex = 0;

        while (startIndex < lines.length && lines[startIndex].trim().startsWith(METADATA_PREFIX)) {
            startIndex++;
        }

        while (startIndex < lines.length && lines[startIndex].trim() === '') {
            startIndex++;
        }

        const filePrompt = lines.slice(startIndex).join('\n').trim();

        if (filePrompt) {
            return { prompt: filePrompt, fromFile: true };
        }
    } catch (e: unknown) {
        if (e instanceof Error && (e as NodeJS.ErrnoException).code !== 'ENOENT') {
            console.warn(chalk.yellow(`⚠️  读取 todo.md 失败: ${e.message}`));
        }
    }

    return { prompt: DEFAULT_PLAN_PROMPT, fromFile: false };
}

export function registerPlanCommand(gitCmd: Command) {
    gitCmd
        .command('plan [prompt...]')
        .description('自动读取最近 10 次提交，由两个 AI (架构师 & 审查员) 协作生成 todo.md')
        .option('-r, --rounds <number>', '对话轮数', '2')
        .option('-m, --model <model>', '架构师模型', 'Assistant')
        .option('--reviewer-model <model>', '审查员模型', 'gemini-2.5-flash-lite')
        .action(async (promptParts, options) => {
            const cliPrompt = promptParts.join(' ').trim();
            const maxRounds = parseInt(options.rounds) || 2;
            const todoPath = path.join(process.cwd(), 'todo.md');

            const { prompt: userPrompt, fromFile } = await resolveUserPrompt(cliPrompt, todoPath);

            const spinner = ora(fromFile ? '正在从 todo.md 读取并初始化分析规划...' : '正在初始化分析规划...').start();

            try {
                const gitService = new GitService();

                if (!(await gitService.isGitRepository())) {
                    spinner.fail('当前目录不是 Git 仓库');
                    return;
                }

                spinner.succeed('Git 仓库验证通过');

                const workflowConfig: WorkflowConfig = {
                    sessionId: Date.now().toString(36) + Math.random().toString(36).substring(2, 11),
                    model: options.model || 'Assistant',
                    capability: CapabilityLevel.SEMANTIC
                };

                const session = new GitWorkflowSession(workflowConfig);
                const planWorkflow = new PlanWorkflow(gitService);

                console.log(chalk.bold.cyan('\n🚀 启动工作流会话...\n'));

                spinner.start('[工作流] 正在执行计划阶段...');

                const result = await session.runPlan(
                    async (input) => planWorkflow.run(input, session.getConfig()),
                    {
                        userPrompt,
                        maxRounds,
                        architectModel: options.model,
                        reviewerModel: options.reviewerModel
                    }
                );

                if (result.success && result.data) {
                    spinner.succeed('计划执行成功');

                    const filePath = path.join(process.cwd(), 'todo.md');

                    const metadataLines = [
                        `> 📅 Generated by Yuangs Git Plan at ${new Date().toLocaleString()}`,
                        `> 🎯 Context: ${userPrompt}`,
                        `> 🔧 Capability Level: ${getCapabilityLevelDisplay(result.data.capability.minCapability)}`,
                        `> ⚙️  Estimated Time: ${result.data.estimatedTime}ms`,
                        `> 📊 Estimated Tokens: ${result.data.estimatedTokens}`,
                        '',
                    ];

                    const fileOutput = metadataLines.join('\n') + result.data.todoMarkdown;

                    fs.writeFileSync(filePath, fileOutput);

                    console.log('');
                    console.log(chalk.green(`✅ 规划完成！文件已生成: ${chalk.bold('todo.md')}`));
                    console.log(chalk.gray(`👉 你可以使用 'code todo.md' 打开查看`));
                    console.log('');
                    console.log(chalk.bold.cyan('📊 会话摘要:'));
                    console.log(chalk.gray(session.getSummary()));

                    session.complete();
                } else {
                    spinner.fail('计划执行失败');

                    if (result.errors && result.errors.length > 0) {
                        console.log('');
                        console.log(chalk.bold.red('❌ 错误详情:'));
                        result.errors.forEach((error, index) => {
                            console.log(chalk.red(`  ${index + 1}. [${error.kind}] ${error.message}`));
                            if (error.suggestions && error.suggestions.length > 0) {
                                error.suggestions.forEach(suggestion => {
                                    console.log(chalk.yellow(`     💡 ${suggestion}`));
                                });
                            }
                        });
                    }

                    if (result.summary) {
                        console.log('');
                        console.log(chalk.gray(`📝 ${result.summary}`));
                    }
                }
            } catch (error: any) {
                spinner.fail(chalk.red(`执行过程中出错: ${error.message}`));

                if (error instanceof AIError) {
                    console.error(chalk.red(`Status: ${error.statusCode}`));
                }

                process.exit(1);
            }
        });
}
