import fs from 'fs';
import path from 'path';

export interface TaskStatus {
    index: number;
    description: string;
    completed: boolean;
    execStatus?: 'pending' | 'in_progress' | 'done' | 'failed';
    reviewScore?: number;
    reviewIssues?: string[];
    attempts?: number;
    backupId?: string;
    dependsOn?: number[];
    priority?: 'high' | 'medium' | 'low';
}

export interface TodoMetadata {
    generatedAt?: string;
    context?: string;
    progress?: { completed: number; total: number };
    currentTask?: number;
}

const METADATA_PREFIX = '>';
const TASK_REGEX = /^[\s]*-\s*\[([x\s])\]\s*(.+?)(?:\s*<!--\s*(.+?)\s*-->)?$/;
const DEPENDENCY_REGEX = /\[depends:\s*(.+?)\]/i;
const PRIORITY_REGEX = /\[priority:\s*(high|medium|low)\]/i;

/**
 * 解析 todo.md 文件
 */
export async function parseTodoFile(filePath: string): Promise<{
    metadata: TodoMetadata;
    tasks: TaskStatus[];
    rawContent: string;
}> {
    const content = await fs.promises.readFile(filePath, 'utf8');
    const lines = content.split('\n');
    
    // 解析元数据
    const metadata: TodoMetadata = {};
    let contentStartIndex = 0;
    
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line.startsWith(METADATA_PREFIX)) {
            contentStartIndex = i;
            break;
        }
        
        // 解析特定元数据
        if (line.includes('Generated by Yuangs Git Plan at')) {
            const match = line.match(/at (.+)$/);
            if (match) {
                metadata.generatedAt = match[1].trim();
            }
        } else if (line.includes('Context:')) {
            metadata.context = line.split('Context:')[1]?.trim();
        } else if (line.includes('Progress:')) {
            const match = line.match(/(\d+)\/(\d+)/);
            if (match) {
                metadata.progress = {
                    completed: parseInt(match[1]),
                    total: parseInt(match[2])
                };
            }
        } else if (line.includes('Current Task:')) {
            metadata.currentTask = parseInt(line.split('Current Task:')[1]?.trim() || '0');
        }
    }
    
    // 解析任务
    const tasks: TaskStatus[] = [];
    const mainContent = lines.slice(contentStartIndex).join('\n');
    
    let taskIndex = 0;
    for (const line of lines.slice(contentStartIndex)) {
        const match = line.match(TASK_REGEX);
        if (match) {
            const [, checkbox, description, comment] = match;
            const task: TaskStatus = {
                index: taskIndex++,
                description: description.trim(),
                completed: checkbox.toLowerCase() === 'x',
                attempts: 0
            };
            
            // 解析描述中的依赖关系
            const depMatch = description.match(DEPENDENCY_REGEX);
            if (depMatch) {
                const depIndices = depMatch[1].split(',')
                    .map(s => parseInt(s.trim()) - 1)
                    .filter(n => !isNaN(n) && n >= 0);
                if (depIndices.length > 0) {
                    task.dependsOn = depIndices;
                }
            }
            
            // 解析描述中的优先级
            const priorityMatch = description.match(PRIORITY_REGEX);
            if (priorityMatch) {
                task.priority = priorityMatch[1] as 'high' | 'medium' | 'low';
            }
            
            // 解析注释中的状态
            if (comment) {
                const execMatch = comment.match(/exec:(\w+)/);
                const reviewMatch = comment.match(/review:(\d+)/);
                const attemptsMatch = comment.match(/attempts:(\d+)/);
                const backupMatch = comment.match(/backup:([a-f0-9]+)/);
                
                if (execMatch) task.execStatus = execMatch[1] as any;
                if (reviewMatch) task.reviewScore = parseInt(reviewMatch[1]);
                if (attemptsMatch) task.attempts = parseInt(attemptsMatch[1]);
                if (backupMatch) task.backupId = backupMatch[1];
            }
            
            tasks.push(task);
        }
    }
    
    return { metadata, tasks, rawContent: content };
}

/**
 * 更新任务状态
 */
export async function updateTaskStatus(
    filePath: string,
    taskIndex: number,
    updates: Partial<TaskStatus>
): Promise<void> {
    const content = await fs.promises.readFile(filePath, 'utf8');
    const lines = content.split('\n');
    
    let currentTaskIndex = 0;
    for (let i = 0; i < lines.length; i++) {
        const match = lines[i].match(TASK_REGEX);
        if (match && currentTaskIndex === taskIndex) {
            const [, checkbox, description] = match;
            
            // 构建新的注释
            const comments: string[] = [];
            if (updates.execStatus) comments.push(`exec:${updates.execStatus}`);
            if (updates.reviewScore !== undefined) comments.push(`review:${updates.reviewScore}`);
            if (updates.attempts !== undefined) comments.push(`attempts:${updates.attempts}`);
            
            const newCheckbox = updates.completed ? 'x' : ' ';
            const commentStr = comments.length > 0 ? ` <!-- ${comments.join(', ')} -->` : '';
            
            lines[i] = `- [${newCheckbox}] ${description}${commentStr}`;
            break;
        }
        if (match) currentTaskIndex++;
    }
    
    await fs.promises.writeFile(filePath, lines.join('\n'), 'utf8');
}

/**
 * 更新元数据
 */
export async function updateMetadata(
    filePath: string,
    updates: Partial<TodoMetadata>
): Promise<void> {
    const content = await fs.promises.readFile(filePath, 'utf8');
    const lines = content.split('\n');
    
    // 找到元数据结束位置
    let metadataEndIndex = 0;
    for (let i = 0; i < lines.length; i++) {
        if (!lines[i].trim().startsWith(METADATA_PREFIX)) {
            metadataEndIndex = i;
            break;
        }
    }
    
    // 更新或添加进度信息
    if (updates.progress) {
        let progressLineIndex = -1;
        for (let i = 0; i < metadataEndIndex; i++) {
            if (lines[i].includes('Progress:')) {
                progressLineIndex = i;
                break;
            }
        }
        
        const progressLine = `> 📊 Progress: ${updates.progress.completed}/${updates.progress.total} tasks completed`;
        if (progressLineIndex >= 0) {
            lines[progressLineIndex] = progressLine;
        } else {
            lines.splice(metadataEndIndex, 0, progressLine);
        }
    }
    
    if (updates.currentTask !== undefined) {
        let currentTaskLineIndex = -1;
        for (let i = 0; i < metadataEndIndex; i++) {
            if (lines[i].includes('Current Task:')) {
                currentTaskLineIndex = i;
                break;
            }
        }
        
        const currentTaskLine = `> 🔄 Current Task: ${updates.currentTask}`;
        if (currentTaskLineIndex >= 0) {
            lines[currentTaskLineIndex] = currentTaskLine;
        } else {
            lines.splice(metadataEndIndex, 0, currentTaskLine);
        }
    }
    
    await fs.promises.writeFile(filePath, lines.join('\n'), 'utf8');
}

/**
 * 获取下一个待执行的任务（考虑依赖关系）
 */
export function getNextTask(tasks: TaskStatus[]): TaskStatus | null {
    const pendingTasks = tasks.filter(t => !t.completed && t.execStatus !== 'failed');
    
    if (pendingTasks.length === 0) {
        return null;
    }
    
    // 检查哪些任务可以执行（所有依赖都已完成）
    const availableTasks = pendingTasks.filter(task => {
        if (!task.dependsOn || task.dependsOn.length === 0) {
            return true;
        }
        
        return task.dependsOn.every(depIndex => {
            const depTask = tasks[depIndex];
            return depTask && depTask.completed;
        });
    });
    
    if (availableTasks.length === 0) {
        // 如果没有可执行的任务，返回第一个失败的任务（如果有）
        const firstFailed = tasks.find(t => t.execStatus === 'failed');
        return firstFailed || null;
    }
    
    // 按优先级排序：high > medium > low
    const priorityOrder = { high: 0, medium: 1, low: 2 };
    availableTasks.sort((a, b) => {
        const priorityA = a.priority ? priorityOrder[a.priority] : 1;
        const priorityB = b.priority ? priorityOrder[b.priority] : 1;
        return priorityA - priorityB;
    });
    
    // 返回优先级最高的可执行任务
    return availableTasks[0];
}

/**
 * 验证任务的依赖关系
 */
export function validateDependencies(tasks: TaskStatus[]): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    
    for (const task of tasks) {
        if (task.dependsOn && task.dependsOn.length > 0) {
            for (const depIndex of task.dependsOn) {
                // 检查依赖索引是否有效
                if (depIndex < 0 || depIndex >= tasks.length) {
                    errors.push(`任务 #${task.index + 1} 依赖了无效的任务索引: ${depIndex + 1}`);
                    continue;
                }
                
                // 检查循环依赖
                if (hasCircularDependency(tasks, task.index, depIndex, new Set())) {
                    errors.push(`检测到循环依赖: 任务 #${task.index + 1} <-> #${depIndex + 1}`);
                }
                
                // 检查自依赖
                if (depIndex === task.index) {
                    errors.push(`任务 #${task.index + 1} 不能依赖自己`);
                }
            }
        }
    }
    
    return { valid: errors.length === 0, errors };
}

/**
 * 检查循环依赖
 */
function hasCircularDependency(
    tasks: TaskStatus[],
    from: number,
    to: number,
    visited: Set<number>
): boolean {
    if (visited.has(to)) {
        return true;
    }
    
    visited.add(to);
    const toTask = tasks[to];
    
    if (!toTask || !toTask.dependsOn) {
        return false;
    }
    
    for (const dep of toTask.dependsOn) {
        if (dep === from || hasCircularDependency(tasks, from, dep, new Set(visited))) {
            return true;
        }
    }
    
    return false;
}

/**
 * 获取任务的执行顺序
 */
export function getExecutionOrder(tasks: TaskStatus[]): number[] {
    const order: number[] = [];
    const visited = new Set<number>();
    
    function visit(index: number) {
        if (visited.has(index)) {
            return;
        }
        
        visited.add(index);
        const task = tasks[index];
        
        // 先访问依赖的任务
        if (task.dependsOn) {
            for (const depIndex of task.dependsOn) {
                visit(depIndex);
            }
        }
        
        order.push(index);
    }
    
    for (let i = 0; i < tasks.length; i++) {
        visit(i);
    }
    
    return order;
}

/**
 * 计算进度
 */
export function calculateProgress(tasks: TaskStatus[]): { completed: number; total: number } {
    return {
        completed: tasks.filter(t => t.completed).length,
        total: tasks.length
    };
}
